In [36]:
import os
import sys
from dataclasses import dataclass
import pandas as pd
from catboost import CatBoostClassifier
from numpy import square
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier,RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.svm import SVC
from sklearn.naive_bayes import  BernoulliNB
import matplotlib.pyplot as plt
import warnings
import numpy as np
import seaborn as sns
import pickle


In [8]:
with open('train_tranform.pkl', 'rb') as f:
     data = pickle.load(f)
with open('target_tranform.pkl', 'rb') as f:
     target = pickle.load(f)
with open('test_tranform.pkl', 'rb') as f:
     test = pickle.load(f)
with open('target_test_tranform.pkl', 'rb') as f:
     target_test = pickle.load(f)


In [9]:
target_test.shape

(7399,)

In [10]:
test.shape

(7399, 57)

In [11]:
data.shape

(29593, 57)

In [12]:
target.shape

(29593,)

In [13]:
def evaluate_model(true, predicted):
    accuracy = accuracy_score(true, predicted)
    classification= classification_report(true, predicted)
    confusion = confusion_matrix(true, predicted)
    return accuracy, classification, confusion

In [14]:
models={
                "Random Forest" : RandomForestClassifier(),
                "Decision Tree" : DecisionTreeClassifier(),
                "Gradient Boosting" : GradientBoostingClassifier(),
                "catBoosting" : CatBoostClassifier(verbose=0),
                "AdaBoosting" : AdaBoostClassifier(),
                "SVM Classifier": SVC(),  # Add SVM for classification
                "Gaussian Naive Bayes": GaussianNB(),          # Gaussian Naive Bayes
                "Bernoulli Naive Bayes": BernoulliNB(),
                "K-Neighbors Classifier": KNeighborsClassifier(),
                "Logistic Regression": LogisticRegression(multi_class='ovr'),

            }

In [21]:
model_list = []
test_accuracy_list = []
for i in range(len(list(models))):
    model = list(models.values())[i]
    model_name = list(models.keys())[i]

    model.fit(data, target)

    y_train_pred = model.predict(data)
    y_test_pred = model.predict(test)

    model_train_accuracy , model_train_classification, model_train_confusion = evaluate_model(target, y_train_pred)
    model_test_accuracy , model_test_classification, model_test_confusion = evaluate_model(target_test, y_test_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model performance for Training set')
    print("- model_train_accuracy: {:.4f}".format(model_train_accuracy))
    print("- model_train_classification:\n", model_train_classification)  # Print classification report as string
    print("- model_train_confusion:\n", model_train_confusion)

    print('----------------------------------')

    print('Model performance for Test set')
    print("- model_test_accuracy: {:.4f}".format(model_test_accuracy))
    print("- model_test_classification:\n", model_test_classification)
    print("- model_test_confusion:\n", model_test_confusion)
    test_accuracy_list.append(model_test_accuracy)

    print('='*35)
    print('\n')



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Random Forest
Model performance for Training set
- model_train_accuracy: 1.0000
- model_train_classification:
               precision    recall  f1-score   support

          -1       1.00      1.00      1.00       927
           1       1.00      1.00      1.00      2146
           2       1.00      1.00      1.00      2193
           3       1.00      1.00      1.00      8337
           4       1.00      1.00      1.00      8165
           5       1.00      1.00      1.00      7825

    accuracy                           1.00     29593
   macro avg       1.00      1.00      1.00     29593
weighted avg       1.00      1.00      1.00     29593

- model_train_confusion:
 [[ 927    0    0    0    0    0]
 [   0 2146    0    0    0    0]
 [   0    0 2193    0    0    0]
 [   0    0    0 8337    0    0]
 [   0    0    0    0 8165    0]
 [   0    0    0    0    0 7825]]
----------------------------------
Model performance for Test set
- model_test_accuracy: 0.7528
- model_test_classificati

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/e

catBoosting
Model performance for Training set
- model_train_accuracy: 0.9142
- model_train_classification:
               precision    recall  f1-score   support

          -1       1.00      0.12      0.21       927
           1       0.94      0.98      0.96      2146
           2       0.96      0.96      0.96      2193
           3       0.94      0.97      0.96      8337
           4       0.91      0.87      0.89      8165
           5       0.87      0.97      0.92      7825

    accuracy                           0.91     29593
   macro avg       0.94      0.81      0.81     29593
weighted avg       0.92      0.91      0.90     29593

- model_train_confusion:
 [[ 107   44   32  271  213  260]
 [   0 2095   51    0    0    0]
 [   0   97 2096    0    0    0]
 [   0    0    0 8086  251    0]
 [   0    0    0  215 7084  866]
 [   0    0    0    0  239 7586]]
----------------------------------
Model performance for Test set
- model_test_accuracy: 0.7505
- model_test_classification

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/m

AdaBoosting
Model performance for Training set
- model_train_accuracy: 0.5869
- model_train_classification:
               precision    recall  f1-score   support

          -1       0.00      0.00      0.00       927
           1       0.00      0.00      0.00      2146
           2       0.50      0.52      0.51      2193
           3       0.70      0.86      0.77      8337
           4       0.48      0.69      0.56      8165
           5       0.67      0.44      0.53      7825

    accuracy                           0.59     29593
   macro avg       0.39      0.42      0.39     29593
weighted avg       0.54      0.59      0.55     29593

- model_train_confusion:
 [[   0    0   50  344  350  183]
 [   0    0 1119  888  139    0]
 [   0    0 1146  903  144    0]
 [   0    0    0 7179 1158    0]
 [   0    0    0 1015 5616 1534]
 [   0    0    0    0 4399 3426]]
----------------------------------
Model performance for Test set
- model_test_accuracy: 0.5831
- model_test_classification

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/m

SVM Classifier
Model performance for Training set
- model_train_accuracy: 0.2817
- model_train_classification:
               precision    recall  f1-score   support

          -1       0.00      0.00      0.00       927
           1       0.00      0.00      0.00      2146
           2       0.00      0.00      0.00      2193
           3       0.28      1.00      0.44      8337
           4       0.00      0.00      0.00      8165
           5       0.00      0.00      0.00      7825

    accuracy                           0.28     29593
   macro avg       0.05      0.17      0.07     29593
weighted avg       0.08      0.28      0.12     29593

- model_train_confusion:
 [[   0    0    0  927    0    0]
 [   0    0    0 2146    0    0]
 [   0    0    0 2193    0    0]
 [   0    0    0 8337    0    0]
 [   0    0    0 8165    0    0]
 [   0    0    0 7825    0    0]]
----------------------------------
Model performance for Test set
- model_test_accuracy: 0.2821
- model_test_classificat

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Bernoulli Naive Bayes
Model performance for Training set
- model_train_accuracy: 0.7128
- model_train_classification:
               precision    recall  f1-score   support

          -1       0.00      0.00      0.00       927
           1       0.56      0.94      0.70      2146
           2       0.82      0.32      0.46      2193
           3       0.82      0.94      0.88      8337
           4       0.81      0.34      0.48      8165
           5       0.64      1.00      0.78      7825

    accuracy                           0.71     29593
   macro avg       0.61      0.59      0.55     29593
weighted avg       0.72      0.71      0.67     29593

- model_train_confusion:
 [[   0  100   22  317  102  386]
 [   0 2011  135    0    0    0]
 [   1 1489  703    0    0    0]
 [   0    0    0 7816  521    0]
 [   0    0    0 1365 2772 4028]
 [   0    0    0    0   33 7792]]
----------------------------------
Model performance for Test set
- model_test_accuracy: 0.7108
- model_test_clas

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Logistic Regression
Model performance for Training set
- model_train_accuracy: 0.5990
- model_train_classification:
               precision    recall  f1-score   support

          -1       0.00      0.00      0.00       927
           1       0.55      0.22      0.31      2146
           2       0.52      0.41      0.46      2193
           3       0.67      0.73      0.70      8337
           4       0.44      0.34      0.38      8165
           5       0.64      0.96      0.77      7825

    accuracy                           0.60     29593
   macro avg       0.47      0.44      0.44     29593
weighted avg       0.56      0.60      0.56     29593

- model_train_confusion:
 [[   0   24   31  297  200  375]
 [   0  469  787  621  261    8]
 [   0  310  902  499  475    7]
 [   0   17    3 6097 2219    1]
 [   0   24    1 1535 2740 3865]
 [   0   14    0    0  292 7519]]
----------------------------------
Model performance for Test set
- model_test_accuracy: 0.5939
- model_test_classi

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/m

In [22]:
test_accuracy_list

[0.7528044330314907,
 0.6888768752534126,
 0.7542911204216786,
 0.7505068252466549,
 0.5830517637518584,
 0.28206514393837007,
 0.6602243546425193,
 0.7107717259089066,
 0.326125152047574,
 0.5938640356804974]

In [23]:
pd.DataFrame(list(zip(model_list, test_accuracy_list)), columns=['Model Name', 'test_accuracy_list']).sort_values(by=["test_accuracy_list"],ascending=False)


Model Name  test_accuracy_list
2       Gradient Boosting            0.754291
0           Random Forest            0.752804
3             catBoosting            0.750507
7   Bernoulli Naive Bayes            0.710772
1           Decision Tree            0.688877
6    Gaussian Naive Bayes            0.660224
9     Logistic Regression            0.593864
4             AdaBoosting            0.583052
8  K-Neighbors Classifier            0.326125
5          SVM Classifier            0.282065

In [45]:
Gradient = GradientBoostingClassifier()
Gradient = Gradient.fit(data, target)
y_pred = Gradient.predict(test)
score = accuracy_score(target_test, y_pred)*100
print(" Accuracy of the model is %.2f" %score)

 Accuracy of the model is 75.43
